import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

const html = fs.readFileSync(new URL('../Index.html', import.meta.url), 'utf8');
const scripts = Array.from(html.matchAll(/<script>([\s\S]*?)<\/script>/g), m => m[1]);

test('all inline scripts parse independently; startup reporter is separate', () => {
  assert.equal(scripts.length, 2);
  scripts.forEach(script => new vm.Script(script));
  assert.match(html, /id="feedback"[^>]*>[^<]+<\/div>/);
});

test('startup script reports a main-script syntax failure without claiming success', () => {
  const listeners = {}, status = {textContent:'', className:''};
  const ctx = vm.createContext({window:{addEventListener:(type,fn)=>{listeners[type]=fn;}}, document:{getElementById:()=>status}});
  vm.runInContext(scripts[0], ctx);
  listeners.error({message:'SyntaxError: missing ) after argument list'});
  assert.equal(status.className,'error');
  assert.match(status.textContent,/再読み込み/);
  assert.doesNotMatch(status.textContent,/保存しました/);
  listeners.unhandledrejection({reason:new Error('connection lost')});
  assert.match(status.textContent,/connection lost/);
});

test('PubMed link generated by real render is complete and safe for a new tab', () => {
  // Run the actual client with a tiny DOM and a non-resolving initial RPC.
  function element(tag='div') {
    return {tag,children:[],textContent:'',value:'',className:'', append(...nodes){this.children.push(...nodes);},
      replaceChildren(...nodes){this.children=nodes;}, setAttribute(name,value){this[name]=value;}};
  }
  const nodes=new Map();
  const ctx=vm.createContext({document:{getElementById:id=>{if(!nodes.has(id))nodes.set(id,element());return nodes.get(id);},
    createElement:tag=>element(tag),querySelectorAll:()=>[]}, URL, Map, console,
    setTimeout:()=>0,clearTimeout:()=>{},google:{script:{run:{withSuccessHandler(){return this;},withFailureHandler(){return this;},listPapers(){}}}}});
  vm.runInContext(scripts[1],ctx);
  vm.runInContext(`current={tabs:{recent:'最近の未確認'},counts:{recent:1},statuses:{unreviewed:'未確認'},boundary:'2026-05-30',today:'2026-08-30',total:1,page_size:50,items:[{pmid:'12345',title:'<img src=x onerror=alert(1)>',topics:'TEST',reference_date:'2026-08-29',review_status:'unreviewed'}]}; render();`,ctx);
  const walk=n=>[n,...n.children.flatMap(walk)];
  const all=walk(nodes.get('papers')),link=all.find(n=>n.tag==='a');
  assert.equal(link.href,'https://pubmed.ncbi.nlm.nih.gov/12345/');
  assert.equal(link.target,'_blank'); assert.equal(link.rel,'noopener noreferrer');
  assert.equal(all.find(n=>n.tag==='h2').textContent,'<img src=x onerror=alert(1)>');
  assert.equal(all.some(n=>n.tag==='img'),false);
  const select=all.find(n=>n.tag==='select');
  assert.deepEqual(select.children.map(n=>n.value),['unreviewed','reviewed_no_fulltext','want_fulltext','fulltext_obtained','read']);
  vm.runInContext(`current.tabs={done:'完了',old:'過去',obtained:'入手済み',want:'希望',recent:'最近'};render();`,ctx);
  assert.deepEqual(nodes.get('tabs').children.map(n=>n.textContent),['最近','希望','入手済み','過去','完了']);
  // HtmlService's delivered script, rather than only local parsing, must also be checked on deploy.
  assert.doesNotMatch(scripts[1], /`https?:\/\//);
});
